export type CountryOption = {
  name: string;
  code: string;
  flag: string;
  continent: string;
};

export const countries: CountryOption[] = [
  { name: "Afghanistan", code: "AF", flag: "🇦🇫", continent: "Asia" },
  { name: "Afrique du Sud", code: "ZA", flag: "🇿🇦", continent: "Africa" },
  { name: "Albanie", code: "AL", flag: "🇦🇱", continent: "Europe" },
  { name: "Algérie", code: "DZ", flag: "🇩🇿", continent: "Africa" },
  { name: "Allemagne", code: "DE", flag: "🇩🇪", continent: "Europe" },
  { name: "Andorre", code: "AD", flag: "🇦🇩", continent: "Europe" },
  { name: "Angola", code: "AO", flag: "🇦🇴", continent: "Africa" },
  { name: "Antigua-et-Barbuda", code: "AG", flag: "🇦🇬", continent: "North America" },
  { name: "Arabie saoudite", code: "SA", flag: "🇸🇦", continent: "Asia" },
  { name: "Argentine", code: "AR", flag: "🇦🇷", continent: "South America" },
  { name: "Arménie", code: "AM", flag: "🇦🇲", continent: "Asia" },
  { name: "Australie", code: "AU", flag: "🇦🇺", continent: "Oceania" },
  { name: "Autriche", code: "AT", flag: "🇦🇹", continent: "Europe" },
  { name: "Azerbaïdjan", code: "AZ", flag: "🇦🇿", continent: "Asia" },
  { name: "Bahamas", code: "BS", flag: "🇧🇸", continent: "North America" },
  { name: "Bahreïn", code: "BH", flag: "🇧🇭", continent: "Asia" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩", continent: "Asia" },
  { name: "Barbade", code: "BB", flag: "🇧🇧", continent: "North America" },
  { name: "Belgique", code: "BE", flag: "🇧🇪", continent: "Europe" },
  { name: "Belize", code: "BZ", flag: "🇧🇿", continent: "North America" },
  { name: "Bénin", code: "BJ", flag: "🇧🇯", continent: "Africa" },
  { name: "Bhoutan", code: "BT", flag: "🇧🇹", continent: "Asia" },
  { name: "Biélorussie", code: "BY", flag: "🇧🇾", continent: "Europe" },
  { name: "Birmanie", code: "MM", flag: "🇲🇲", continent: "Asia" },
  { name: "Bolivie", code: "BO", flag: "🇧🇴", continent: "South America" },
  { name: "Bosnie-Herzégovine", code: "BA", flag: "🇧🇦", continent: "Europe" },
  { name: "Botswana", code: "BW", flag: "🇧🇼", continent: "Africa" },
  { name: "Brésil", code: "BR", flag: "🇧🇷", continent: "South America" },
  { name: "Brunei", code: "BN", flag: "🇧🇳", continent: "Asia" },
  { name: "Bulgarie", code: "BG", flag: "🇧🇬", continent: "Europe" },
  { name: "Burkina Faso", code: "BF", flag: "🇧🇫", continent: "Africa" },
  { name: "Burundi", code: "BI", flag: "🇧🇮", continent: "Africa" },
  { name: "Cambodge", code: "KH", flag: "🇰🇭", continent: "Asia" },
  { name: "Cameroun", code: "CM", flag: "🇨🇲", continent: "Africa" },
  { name: "Canada", code: "CA", flag: "🇨🇦", continent: "North America" },
  { name: "Cap-Vert", code: "CV", flag: "🇨🇻", continent: "Africa" },
  { name: "Chili", code: "CL", flag: "🇨🇱", continent: "South America" },
  { name: "Chine", code: "CN", flag: "🇨🇳", continent: "Asia" },
  { name: "Chypre", code: "CY", flag: "🇨🇾", continent: "Europe" },
  { name: "Colombie", code: "CO", flag: "🇨🇴", continent: "South America" },
  { name: "Comores", code: "KM", flag: "🇰🇲", continent: "Africa" },
  { name: "Congo", code: "CG", flag: "🇨🇬", continent: "Africa" },
  { name: "Congo (RDC)", code: "CD", flag: "🇨🇩", continent: "Africa" },
  { name: "Corée du Nord", code: "KP", flag: "🇰🇵", continent: "Asia" },
  { name: "Corée du Sud", code: "KR", flag: "🇰🇷", continent: "Asia" },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷", continent: "North America" },
  { name: "Côte d'Ivoire", code: "CI", flag: "🇨🇮", continent: "Africa" },
  { name: "Croatie", code: "HR", flag: "🇭🇷", continent: "Europe" },
  { name: "Cuba", code: "CU", flag: "🇨🇺", continent: "North America" },
  { name: "Danemark", code: "DK", flag: "🇩🇰", continent: "Europe" },
  { name: "Djibouti", code: "DJ", flag: "🇩🇯", continent: "Africa" },
  { name: "Dominique", code: "DM", flag: "🇩🇲", continent: "North America" },
  { name: "Égypte", code: "EG", flag: "🇪🇬", continent: "Africa" },
  { name: "Émirats arabes unis", code: "AE", flag: "🇦🇪", continent: "Asia" },
  { name: "Équateur", code: "EC", flag: "🇪🇨", continent: "South America" },
  { name: "Érythrée", code: "ER", flag: "🇪🇷", continent: "Africa" },
  { name: "Espagne", code: "ES", flag: "🇪🇸", continent: "Europe" },
  { name: "Estonie", code: "EE", flag: "🇪🇪", continent: "Europe" },
  { name: "Eswatini", code: "SZ", flag: "🇸🇿", continent: "Africa" },
  { name: "États-Unis", code: "US", flag: "🇺🇸", continent: "North America" },
  { name: "Éthiopie", code: "ET", flag: "🇪🇹", continent: "Africa" },
  { name: "Fidji", code: "FJ", flag: "🇫🇯", continent: "Oceania" },
  { name: "Finlande", code: "FI", flag: "🇫🇮", continent: "Europe" },
  { name: "France", code: "FR", flag: "🇫🇷", continent: "Europe" },
  { name: "Gabon", code: "GA", flag: "🇬🇦", continent: "Africa" },
  { name: "Gambie", code: "GM", flag: "🇬🇲", continent: "Africa" },
  { name: "Géorgie", code: "GE", flag: "🇬🇪", continent: "Asia" },
  { name: "Ghana", code: "GH", flag: "🇬🇭", continent: "Africa" },
  { name: "Grèce", code: "GR", flag: "🇬🇷", continent: "Europe" },
  { name: "Grenade", code: "GD", flag: "🇬🇩", continent: "North America" },
  { name: "Guatemala", code: "GT", flag: "🇬🇹", continent: "North America" },
  { name: "Guinée", code: "GN", flag: "🇬🇳", continent: "Africa" },
  { name: "Guinée-Bissau", code: "GW", flag: "🇬🇼", continent: "Africa" },
  { name: "Guinée équatoriale", code: "GQ", flag: "🇬🇶", continent: "Africa" },
  { name: "Guyana", code: "GY", flag: "🇬🇾", continent: "South America" },
  { name: "Haïti", code: "HT", flag: "🇭🇹", continent: "North America" },
  { name: "Honduras", code: "HN", flag: "🇭🇳", continent: "North America" },
  { name: "Hongrie", code: "HU", flag: "🇭🇺", continent: "Europe" },
  { name: "Îles Marshall", code: "MH", flag: "🇲🇭", continent: "Oceania" },
  { name: "Îles Salomon", code: "SB", flag: "🇸🇧", continent: "Oceania" },
  { name: "Inde", code: "IN", flag: "🇮🇳", continent: "Asia" },
  { name: "Indonésie", code: "ID", flag: "🇮🇩", continent: "Asia" },
  { name: "Irak", code: "IQ", flag: "🇮🇶", continent: "Asia" },
  { name: "Iran", code: "IR", flag: "🇮🇷", continent: "Asia" },
  { name: "Irlande", code: "IE", flag: "🇮🇪", continent: "Europe" },
  { name: "Islande", code: "IS", flag: "🇮🇸", continent: "Europe" },
  { name: "Israël", code: "IL", flag: "🇮🇱", continent: "Asia" },
  { name: "Italie", code: "IT", flag: "🇮🇹", continent: "Europe" },
  { name: "Jamaïque", code: "JM", flag: "🇯🇲", continent: "North America" },
  { name: "Japon", code: "JP", flag: "🇯🇵", continent: "Asia" },
  { name: "Jordanie", code: "JO", flag: "🇯🇴", continent: "Asia" },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿", continent: "Asia" },
  { name: "Kenya", code: "KE", flag: "🇰🇪", continent: "Africa" },
  { name: "Kirghizistan", code: "KG", flag: "🇰🇬", continent: "Asia" },
  { name: "Kiribati", code: "KI", flag: "🇰🇮", continent: "Oceania" },
  { name: "Kosovo", code: "XK", flag: "🇽🇰", continent: "Europe" },
  { name: "Koweït", code: "KW", flag: "🇰🇼", continent: "Asia" },
  { name: "Laos", code: "LA", flag: "🇱🇦", continent: "Asia" },
  { name: "Lesotho", code: "LS", flag: "🇱🇸", continent: "Africa" },
  { name: "Lettonie", code: "LV", flag: "🇱🇻", continent: "Europe" },
  { name: "Liban", code: "LB", flag: "🇱🇧", continent: "Asia" },
  { name: "Liberia", code: "LR", flag: "🇱🇷", continent: "Africa" },
  { name: "Libye", code: "LY", flag: "🇱🇾", continent: "Africa" },
  { name: "Liechtenstein", code: "LI", flag: "🇱🇮", continent: "Europe" },
  { name: "Lituanie", code: "LT", flag: "🇱🇹", continent: "Europe" },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺", continent: "Europe" },
  { name: "Macédoine du Nord", code: "MK", flag: "🇲🇰", continent: "Europe" },
  { name: "Madagascar", code: "MG", flag: "🇲🇬", continent: "Africa" },
  { name: "Malaisie", code: "MY", flag: "🇲🇾", continent: "Asia" },
  { name: "Malawi", code: "MW", flag: "🇲🇼", continent: "Africa" },
  { name: "Maldives", code: "MV", flag: "🇲🇻", continent: "Asia" },
  { name: "Mali", code: "ML", flag: "🇲🇱", continent: "Africa" },
  { name: "Malte", code: "MT", flag: "🇲🇹", continent: "Europe" },
  { name: "Maroc", code: "MA", flag: "🇲🇦", continent: "Africa" },
  { name: "Maurice", code: "MU", flag: "🇲🇺", continent: "Africa" },
  { name: "Mauritanie", code: "MR", flag: "🇲🇷", continent: "Africa" },
  { name: "Mexique", code: "MX", flag: "🇲🇽", continent: "North America" },
  { name: "Micronésie", code: "FM", flag: "🇫🇲", continent: "Oceania" },
  { name: "Moldavie", code: "MD", flag: "🇲🇩", continent: "Europe" },
  { name: "Monaco", code: "MC", flag: "🇲🇨", continent: "Europe" },
  { name: "Mongolie", code: "MN", flag: "🇲🇳", continent: "Asia" },
  { name: "Monténégro", code: "ME", flag: "🇲🇪", continent: "Europe" },
  { name: "Mozambique", code: "MZ", flag: "🇲🇿", continent: "Africa" },
  { name: "Namibie", code: "NA", flag: "🇳🇦", continent: "Africa" },
  { name: "Nauru", code: "NR", flag: "🇳🇷", continent: "Oceania" },
  { name: "Népal", code: "NP", flag: "🇳🇵", continent: "Asia" },
  { name: "Nicaragua", code: "NI", flag: "🇳🇮", continent: "North America" },
  { name: "Niger", code: "NE", flag: "🇳🇪", continent: "Africa" },
  { name: "Nigéria", code: "NG", flag: "🇳🇬", continent: "Africa" },
  { name: "Norvège", code: "NO", flag: "🇳🇴", continent: "Europe" },
  { name: "Nouvelle-Zélande", code: "NZ", flag: "🇳🇿", continent: "Oceania" },
  { name: "Oman", code: "OM", flag: "🇴🇲", continent: "Asia" },
  { name: "Ouganda", code: "UG", flag: "🇺🇬", continent: "Africa" },
  { name: "Ouzbékistan", code: "UZ", flag: "🇺🇿", continent: "Asia" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰", continent: "Asia" },
  { name: "Palaos", code: "PW", flag: "🇵🇼", continent: "Oceania" },
  { name: "Palestine", code: "PS", flag: "🇵🇸", continent: "Asia" },
  { name: "Panama", code: "PA", flag: "🇵🇦", continent: "North America" },
  { name: "Papouasie-Nouvelle-Guinée", code: "PG", flag: "🇵🇬", continent: "Oceania" },
  { name: "Paraguay", code: "PY", flag: "🇵🇾", continent: "South America" },
  { name: "Pays-Bas", code: "NL", flag: "🇳🇱", continent: "Europe" },
  { name: "Pérou", code: "PE", flag: "🇵🇪", continent: "South America" },
  { name: "Philippines", code: "PH", flag: "🇵🇭", continent: "Asia" },
  { name: "Pologne", code: "PL", flag: "🇵🇱", continent: "Europe" },
  { name: "Portugal", code: "PT", flag: "🇵🇹", continent: "Europe" },
  { name: "Qatar", code: "QA", flag: "🇶🇦", continent: "Asia" },
  { name: "République centrafricaine", code: "CF", flag: "🇨🇫", continent: "Africa" },
  { name: "République dominicaine", code: "DO", flag: "🇩🇴", continent: "North America" },
  { name: "Roumanie", code: "RO", flag: "🇷🇴", continent: "Europe" },
  { name: "Royaume-Uni", code: "GB", flag: "🇬🇧", continent: "Europe" },
  { name: "Russie", code: "RU", flag: "🇷🇺", continent: "Europe" },
  { name: "Rwanda", code: "RW", flag: "🇷🇼", continent: "Africa" },
  { name: "Saint-Kitts-et-Nevis", code: "KN", flag: "🇰🇳", continent: "North America" },
  { name: "Saint-Marin", code: "SM", flag: "🇸🇲", continent: "Europe" },
  { name: "Saint-Vincent-et-les-Grenadines", code: "VC", flag: "🇻🇨", continent: "North America" },
  { name: "Sainte-Lucie", code: "LC", flag: "🇱🇨", continent: "North America" },
  { name: "Salvador", code: "SV", flag: "🇸🇻", continent: "North America" },
  { name: "Samoa", code: "WS", flag: "🇼🇸", continent: "Oceania" },
  { name: "Sao Tomé-et-Principe", code: "ST", flag: "🇸🇹", continent: "Africa" },
  { name: "Sénégal", code: "SN", flag: "🇸🇳", continent: "Africa" },
  { name: "Serbie", code: "RS", flag: "🇷🇸", continent: "Europe" },
  { name: "Seychelles", code: "SC", flag: "🇸🇨", continent: "Africa" },
  { name: "Sierra Leone", code: "SL", flag: "🇸🇱", continent: "Africa" },
  { name: "Singapour", code: "SG", flag: "🇸🇬", continent: "Asia" },
  { name: "Slovaquie", code: "SK", flag: "🇸🇰", continent: "Europe" },
  { name: "Slovénie", code: "SI", flag: "🇸🇮", continent: "Europe" },
  { name: "Somalie", code: "SO", flag: "🇸🇴", continent: "Africa" },
  { name: "Soudan", code: "SD", flag: "🇸🇩", continent: "Africa" },
  { name: "Soudan du Sud", code: "SS", flag: "🇸🇸", continent: "Africa" },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰", continent: "Asia" },
  { name: "Suède", code: "SE", flag: "🇸🇪", continent: "Europe" },
  { name: "Suisse", code: "CH", flag: "🇨🇭", continent: "Europe" },
  { name: "Suriname", code: "SR", flag: "🇸🇷", continent: "South America" },
  { name: "Syrie", code: "SY", flag: "🇸🇾", continent: "Asia" },
  { name: "Tadjikistan", code: "TJ", flag: "🇹🇯", continent: "Asia" },
  { name: "Taïwan", code: "TW", flag: "🇹🇼", continent: "Asia" },
  { name: "Tanzanie", code: "TZ", flag: "🇹🇿", continent: "Africa" },
  { name: "Tchad", code: "TD", flag: "🇹🇩", continent: "Africa" },
  { name: "Tchéquie", code: "CZ", flag: "🇨🇿", continent: "Europe" },
  { name: "Thaïlande", code: "TH", flag: "🇹🇭", continent: "Asia" },
  { name: "Timor oriental", code: "TL", flag: "🇹🇱", continent: "Asia" },
  { name: "Togo", code: "TG", flag: "🇹🇬", continent: "Africa" },
  { name: "Tonga", code: "TO", flag: "🇹🇴", continent: "Oceania" },
  { name: "Trinité-et-Tobago", code: "TT", flag: "🇹🇹", continent: "North America" },
  { name: "Tunisie", code: "TN", flag: "🇹🇳", continent: "Africa" },
  { name: "Turkménistan", code: "TM", flag: "🇹🇲", continent: "Asia" },
  { name: "Turquie", code: "TR", flag: "🇹🇷", continent: "Asia" },
  { name: "Tuvalu", code: "TV", flag: "🇹🇻", continent: "Oceania" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦", continent: "Europe" },
  { name: "Uruguay", code: "UY", flag: "🇺🇾", continent: "South America" },
  { name: "Vanuatu", code: "VU", flag: "🇻🇺", continent: "Oceania" },
  { name: "Vatican", code: "VA", flag: "🇻🇦", continent: "Europe" },
  { name: "Venezuela", code: "VE", flag: "🇻🇪", continent: "South America" },
  { name: "Viêt Nam", code: "VN", flag: "🇻🇳", continent: "Asia" },
  { name: "Yémen", code: "YE", flag: "🇾🇪", continent: "Asia" },
  { name: "Zambie", code: "ZM", flag: "🇿🇲", continent: "Africa" },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼", continent: "Africa" },
].sort((a, b) => a.name.localeCompare(b.name, "fr"));

export function getCountryByCode(code: string): CountryOption | undefined {
  return countries.find((c) => c.code === code.toUpperCase());
}

export function isValidCountryCode(code: string): boolean {
  return countries.some((c) => c.code === code.toUpperCase());
}

export function getCountryName(code: string): string | undefined {
  return getCountryByCode(code)?.name;
}
