-- Add streak tracking fields to User
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastActiveDate" TIMESTAMPTZ;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "currentStreak" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "longestStreak" INTEGER NOT NULL DEFAULT 0;
